### ISSUE TITLE
Script not working Can't understand error

### ISSUE THREAD

**Issue by AgentZoy** [blackophelia/puppet-nagios-checks#1]
Hi
Trying to launch check_puppet_nodes.py with necessary parametrs under Linux With latest python 2.7 I got error
/puppet-nagios-checks.py -H 127.0.0.1 -p 8080
Traceback (most recent call last):
  File "./puppet-nagios-checks.py", line 151, in <module>
    main()
  File "./puppet-nagios-checks.py", line 125, in main
    exit_code, message = get_node_status()
  File "./puppet-nagios-checks.py", line 115, in get_node_status
    node_status_totals[s['latest_report_status']] += 1
KeyError: None

I'm not so expert in Python ((
What I done Incorrectly

But I assume script give necessary info for me

**Comment by blackophelia** [comment]
Hi,

I think this the check_puppet_nodes script you're running?

The error suggest to me that it isn't getting any data back from puppet...   on line 115, it's reading data from a list (array) - s['latest_report_status'].  This is data that is sent back from puppet, and it's being accessed in the loop.

It's been a long time since I've looked at this!

**Comment by AgentZoy** [comment]
Thanks
It's mean puppet problem?

**Comment by AgentZoy** [comment]
`curl --silent -G -H "Content-type:application/json" 'http://127.0.0.1:8080/pdb/query/v4/nodes' --data-urlencode 'query=["=","latest_report_status","failed"]'`

is sucessfull and get data from puppetboard

**Comment by AgentZoy** [comment]
Can you please help me It's only one script that do what I need

**Comment by AgentZoy** [comment]
port is opened All components of puppet instaaled on one machine

**Comment by blackophelia** [comment]
Yes, I think it might be your puppet setup.

You can look at the http request that’s executed and try run that manually
in the browser, to see if you get results.

**Comment by AgentZoy** [comment]
Hi
I modified code that url formed correctly
But I got the same error
As I understand code it's error raises when no key in vocabulary
Or As I understand script cant find it in json
Trying to fix not sucessfull
Traceback (most recent call last):
  File "./puppet-nagios-checks.py", line 152, in <module>
    main()
  File "./puppet-nagios-checks.py", line 126, in main
    exit_code, message = get_node_status()
  File "./puppet-nagios-checks.py", line 117, in get_node_status
    node_status_totals[s['latest_report_status']] += 1
KeyError: None

**Comment by AgentZoy** [comment]
https://realpython.com/python-keyerror/

**Comment by blackophelia** [comment]
I think you need to start with the information puppet is returning.

The script executes this request against puppet.  Try run the curl command below... change hostname and port to be your puppet host name and port.


curl http://<hostname>:<port>/pdb/query/v4/nodes

This should return some JSON output from puppet.  If this doesn't return any information, then that's likely to be the problem.


Also, this was written for puppet version 4, and I'm not able to support newer puppet versions, as I no longer have access to a puppet environment.

What version of puppet are you running?

**Comment by AgentZoy** [comment]
`curl --silent -G -H "Content-type:application/json" 'http://127.0.0.1:8080/pdb/query/v4/nodes' --data-urlencode 'query=["=","latest_report_status","failed"]'` returns json result

puppet version is 4

**Comment by blackophelia** [comment]
What result do you get without the query filter?  The script will execute without the query so that it gets all nodes returned.

**Comment by AgentZoy** [comment]
I get all nodes status in json format witj statuses and other information
